import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: '',
  description: 'Generated by Next.js',
}

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'vi' }]
}

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body>
        lol
        {children}
        </body>
    </html>
  )
}
